package com.asus.wellness.utils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.annotations.Expose;

/**
 * Entity mapped to table step_count.
 */
public class Step_count {

    private Long id;
    @Expose
    private Long start;
    @Expose
    private Long end;
    @Expose
    private Long step_count;

    public Step_count() {
    }

    public Step_count(Long id) {
        this.id = id;
    }

    public Step_count(Long id, Long start, Long end, Long step_count) {
        this.id = id;
        this.start = start;
        this.end = end;
        this.step_count = step_count;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStart() {
        return start;
    }

    public void setStart(Long start) {
        this.start = start;
    }

    public Long getEnd() {
        return end;
    }

    public void setEnd(Long end) {
        this.end = end;
    }

    public Long getStep_count() {
        return step_count;
    }

    public void setStep_count(Long step_count) {
        this.step_count = step_count;
    }

}
