package com.asus.wellness.utils;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.annotations.Expose;

/**
 * Entity mapped to table device.
 */
public class Device {
    @Expose
    private Long id;
    @Expose
    private String name;
    @Expose
    private String blueaddr;
    @Expose
    private Boolean isRobin;
    @Expose
    private Long lastconnecttime;
    @Expose
    private Long stepsynctime;
    @Expose
    private Long ecgsynctime;

    private Long todaySteps;

    public Device() {
    }

    public Device(Long id) {
        this.id = id;
    }

    public Device(Long id, String name, String blueaddr, Boolean isRobin, Long lastconnecttime,Long stepsynctime, Long ecgsynctime) {
        this.id = id;
        this.name = name;
        this.blueaddr = blueaddr;
        this.isRobin = isRobin;
        this.lastconnecttime = lastconnecttime;
        this.stepsynctime = stepsynctime;
        this.ecgsynctime = ecgsynctime;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getBlueaddr() {
        return blueaddr;
    }

    public void setBlueaddr(String blueaddr) {
        this.blueaddr = blueaddr;
    }

    public Boolean getIsRobin() {
        return isRobin;
    }

    public void setIsRobin(Boolean isRobin) {
        this.isRobin = isRobin;
    }

    public Long getLastconnecttime() {
        return lastconnecttime;
    }

    public void setLastconnecttime(Long lastconnecttime) {
        this.lastconnecttime = lastconnecttime;
    }

    public Long getStepsynctime() {
        return stepsynctime;
    }

    public void setStepsynctime(Long stepsynctime) {
        this.stepsynctime = stepsynctime;
    }

    public Long getEcgsynctime() {
        return ecgsynctime;
    }

    public void setEcgsynctime(Long ecgsynctime) {
        this.ecgsynctime = ecgsynctime;
    }

    public void setTodaySteps(Long todaySteps)
    {
        this.todaySteps = todaySteps;
    }
    public Long getTodaySteps()
    {
        return todaySteps;
    }
}
