package com.asus.sharedata;



// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.annotations.Expose;

/**
 * Entity mapped to table ecg.
 */
public class SleepSyncItem {


    @Expose
    private Long measure_time;
    @Expose
    private Long measure_value;
    @Expose
    private Long measure_type;
    @Expose
    private String measure_comment;
    private Long deviceId;


    public SleepSyncItem(Long measure_time, Long measure_value, Long measure_type, String measure_comment) {

        this.measure_time = measure_time;
        this.measure_value = measure_value;
        this.measure_type = measure_type;
        this.measure_comment = measure_comment;
    }
    public SleepSyncItem(Long id, Long measure_time, Long measure_value, Long measure_type, String measure_comment, Long deviceId) {
        this.measure_time = measure_time;
        this.measure_value = measure_value;
        this.measure_type = measure_type;
        this.measure_comment = measure_comment;
        this.deviceId = deviceId;
    }



    public Long getMeasure_time() {
        return measure_time;
    }

    public void setMeasure_time(Long measure_time) {
        this.measure_time = measure_time;
    }

    public Long getMeasure_value() {
        return measure_value;
    }

    public void setMeasure_value(Long measure_value) {
        this.measure_value = measure_value;
    }

    public Long getMeasure_type() {
        return measure_type;
    }

    public void setMeasure_type(Long measure_type) {
        this.measure_type = measure_type;
    }

    public String getMeasure_comment() {
        return measure_comment;
    }

    public void setMeasure_comment(String measure_comment) {
        this.measure_comment = measure_comment;
    }

    public Long getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(Long deviceId) {
        this.deviceId = deviceId;
    }

}
