package com.asus.wellness.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table activity_status.
 */
public class Activity_status {

    private Long id;
    private Long step;
    private Long distance;
    private Long activity_type;

    public Activity_status() {
    }

    public Activity_status(Long id) {
        this.id = id;
    }

    public Activity_status(Long id, Long step, Long distance, Long activity_type) {
        this.id = id;
        this.step = step;
        this.distance = distance;
        this.activity_type = activity_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStep() {
        return step;
    }

    public void setStep(Long step) {
        this.step = step;
    }

    public Long getDistance() {
        return distance;
    }

    public void setDistance(Long distance) {
        this.distance = distance;
    }

    public Long getActivity_type() {
        return activity_type;
    }

    public void setActivity_type(Long activity_type) {
        this.activity_type = activity_type;
    }

}
