package com.asus.wellness.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table coach_item.
 */
public class CoachItem {

    private long coach_id;
    private long start;
    private Long end;
    private Long value;

    public CoachItem() {
    }

    public CoachItem(long start) {
        this.start = start;
    }

    public CoachItem(long coach_id, long start, Long end, Long value) {
        this.coach_id = coach_id;
        this.start = start;
        this.end = end;
        this.value = value;
    }

    public long getCoach_id() {
        return coach_id;
    }

    public void setCoach_id(long coach_id) {
        this.coach_id = coach_id;
    }

    public long getStart() {
        return start;
    }

    public void setStart(long start) {
        this.start = start;
    }

    public Long getEnd() {
        return end;
    }

    public void setEnd(Long end) {
        this.end = end;
    }

    public Long getValue() {
        return value;
    }

    public void setValue(Long value) {
        this.value = value;
    }

}
