package com.asus.wellness.dbhelper;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.asus.wellness.dbhelper.Profile;
import com.asus.wellness.dbhelper.SystemInfo;
import com.asus.wellness.dbhelper.Activity_status;
import com.asus.wellness.dbhelper.Ecg;
import com.asus.wellness.dbhelper.Step_count;
import com.asus.wellness.dbhelper.Coach;
import com.asus.wellness.dbhelper.CoachItem;
import com.asus.wellness.dbhelper.Sleep;

import com.asus.wellness.dbhelper.ProfileDao;
import com.asus.wellness.dbhelper.SystemInfoDao;
import com.asus.wellness.dbhelper.Activity_statusDao;
import com.asus.wellness.dbhelper.EcgDao;
import com.asus.wellness.dbhelper.Step_countDao;
import com.asus.wellness.dbhelper.CoachDao;
import com.asus.wellness.dbhelper.CoachItemDao;
import com.asus.wellness.dbhelper.SleepDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig profileDaoConfig;
    private final DaoConfig systemInfoDaoConfig;
    private final DaoConfig activity_statusDaoConfig;
    private final DaoConfig ecgDaoConfig;
    private final DaoConfig step_countDaoConfig;
    private final DaoConfig coachDaoConfig;
    private final DaoConfig coachItemDaoConfig;
    private final DaoConfig sleepDaoConfig;

    private final ProfileDao profileDao;
    private final SystemInfoDao systemInfoDao;
    private final Activity_statusDao activity_statusDao;
    private final EcgDao ecgDao;
    private final Step_countDao step_countDao;
    private final CoachDao coachDao;
    private final CoachItemDao coachItemDao;
    private final SleepDao sleepDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        profileDaoConfig = daoConfigMap.get(ProfileDao.class).clone();
        profileDaoConfig.initIdentityScope(type);

        systemInfoDaoConfig = daoConfigMap.get(SystemInfoDao.class).clone();
        systemInfoDaoConfig.initIdentityScope(type);

        activity_statusDaoConfig = daoConfigMap.get(Activity_statusDao.class).clone();
        activity_statusDaoConfig.initIdentityScope(type);

        ecgDaoConfig = daoConfigMap.get(EcgDao.class).clone();
        ecgDaoConfig.initIdentityScope(type);

        step_countDaoConfig = daoConfigMap.get(Step_countDao.class).clone();
        step_countDaoConfig.initIdentityScope(type);

        coachDaoConfig = daoConfigMap.get(CoachDao.class).clone();
        coachDaoConfig.initIdentityScope(type);

        coachItemDaoConfig = daoConfigMap.get(CoachItemDao.class).clone();
        coachItemDaoConfig.initIdentityScope(type);

        sleepDaoConfig = daoConfigMap.get(SleepDao.class).clone();
        sleepDaoConfig.initIdentityScope(type);

        profileDao = new ProfileDao(profileDaoConfig, this);
        systemInfoDao = new SystemInfoDao(systemInfoDaoConfig, this);
        activity_statusDao = new Activity_statusDao(activity_statusDaoConfig, this);
        ecgDao = new EcgDao(ecgDaoConfig, this);
        step_countDao = new Step_countDao(step_countDaoConfig, this);
        coachDao = new CoachDao(coachDaoConfig, this);
        coachItemDao = new CoachItemDao(coachItemDaoConfig, this);
        sleepDao = new SleepDao(sleepDaoConfig, this);

        registerDao(Profile.class, profileDao);
        registerDao(SystemInfo.class, systemInfoDao);
        registerDao(Activity_status.class, activity_statusDao);
        registerDao(Ecg.class, ecgDao);
        registerDao(Step_count.class, step_countDao);
        registerDao(Coach.class, coachDao);
        registerDao(CoachItem.class, coachItemDao);
        registerDao(Sleep.class, sleepDao);
    }
    
    public void clear() {
        profileDaoConfig.getIdentityScope().clear();
        systemInfoDaoConfig.getIdentityScope().clear();
        activity_statusDaoConfig.getIdentityScope().clear();
        ecgDaoConfig.getIdentityScope().clear();
        step_countDaoConfig.getIdentityScope().clear();
        coachDaoConfig.getIdentityScope().clear();
        coachItemDaoConfig.getIdentityScope().clear();
        sleepDaoConfig.getIdentityScope().clear();
    }

    public ProfileDao getProfileDao() {
        return profileDao;
    }

    public SystemInfoDao getSystemInfoDao() {
        return systemInfoDao;
    }

    public Activity_statusDao getActivity_statusDao() {
        return activity_statusDao;
    }

    public EcgDao getEcgDao() {
        return ecgDao;
    }

    public Step_countDao getStep_countDao() {
        return step_countDao;
    }

    public CoachDao getCoachDao() {
        return coachDao;
    }

    public CoachItemDao getCoachItemDao() {
        return coachItemDao;
    }

    public SleepDao getSleepDao() {
        return sleepDao;
    }

}
