package com.asus.wellness.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table ecg.
 */
public class Ecg {

    private Long id;
    private Long measure_time;
    private Long measure_value;
    private Long measure_type;

    public Ecg() {
    }

    public Ecg(Long id) {
        this.id = id;
    }

    public Ecg(Long id, Long measure_time, Long measure_value, Long measure_type) {
        this.id = id;
        this.measure_time = measure_time;
        this.measure_value = measure_value;
        this.measure_type = measure_type;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getMeasure_time() {
        return measure_time;
    }

    public void setMeasure_time(Long measure_time) {
        this.measure_time = measure_time;
    }

    public Long getMeasure_value() {
        return measure_value;
    }

    public void setMeasure_value(Long measure_value) {
        this.measure_value = measure_value;
    }

    public Long getMeasure_type() {
        return measure_type;
    }

    public void setMeasure_type(Long measure_type) {
        this.measure_type = measure_type;
    }

}
