package com.asus.wellness.dbhelper;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.asus.wellness.dbhelper.Ecg;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table ecg.
*/
public class EcgDao extends AbstractDao<Ecg, Long> {

    public static final String TABLENAME = "ecg";

    /**
     * Properties of entity Ecg.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Measure_time = new Property(1, Long.class, "measure_time", false, "measure_time");
        public final static Property Measure_value = new Property(2, Long.class, "measure_value", false, "measure_value");
        public final static Property Measure_type = new Property(3, Long.class, "measure_type", false, "measure_type");
    };


    public EcgDao(DaoConfig config) {
        super(config);
    }
    
    public EcgDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'ecg' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'measure_time' INTEGER," + // 1: measure_time
                "'measure_value' INTEGER," + // 2: measure_value
                "'measure_type' INTEGER);"); // 3: measure_type
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'ecg'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Ecg entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long measure_time = entity.getMeasure_time();
        if (measure_time != null) {
            stmt.bindLong(2, measure_time);
        }
 
        Long measure_value = entity.getMeasure_value();
        if (measure_value != null) {
            stmt.bindLong(3, measure_value);
        }
 
        Long measure_type = entity.getMeasure_type();
        if (measure_type != null) {
            stmt.bindLong(4, measure_type);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Ecg readEntity(Cursor cursor, int offset) {
        Ecg entity = new Ecg( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // measure_time
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2), // measure_value
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3) // measure_type
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Ecg entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMeasure_time(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setMeasure_value(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
        entity.setMeasure_type(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Ecg entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Ecg entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
