package com.asus.wellness.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import android.util.Log;

import com.asus.wellness.microprovider.ProfileTable;
import com.asus.wellness.utils.ProfileHelper;
// KEEP INCLUDES END
/**
 * Entity mapped to table profile.
 */
public class Profile {

    private Long id;
    private String name;
    private String photo_path;
    private Integer age;
    private Integer gender;
    private Integer height;
    private Integer height_unit;
    private Integer weight;
    private Integer weight_unit;
    private Long start_time;
    private Integer step_goal;
    private Integer next_step_goal;
    private Integer distance_unit;
    private Boolean isprofileset;
    private Long stepsynctime;
    private Long ecgsynctime;
    private byte[] photodata;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Profile() {
    }

    public Profile(Long id) {
        this.id = id;
    }

    public Profile(Long id, String name, String photo_path, Integer age, Integer gender, Integer height, Integer height_unit, Integer weight, Integer weight_unit, Long start_time, Integer step_goal, Integer next_step_goal, Integer distance_unit, Boolean isprofileset, Long stepsynctime, Long ecgsynctime, byte[] photodata) {
        this.id = id;
        this.name = name;
        this.photo_path = photo_path;
        this.age = age;
        this.gender = gender;
        this.height = height;
        this.height_unit = height_unit;
        this.weight = weight;
        this.weight_unit = weight_unit;
        this.start_time = start_time;
        this.step_goal = step_goal;
        this.next_step_goal = next_step_goal;
        this.distance_unit = distance_unit;
        this.isprofileset = isprofileset;
        this.stepsynctime = stepsynctime;
        this.ecgsynctime = ecgsynctime;
        this.photodata = photodata;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }



    public void setPhoto_path(String photo_path) {
        this.photo_path = photo_path;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getGender() {
        return gender;
    }
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public void setHeight_unit(Integer height_unit) {
        this.height_unit = height_unit;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public void setWeight_unit(Integer weight_unit) {
        this.weight_unit = weight_unit;
    }

    public Long getStart_time() {
        return start_time;
    }

    public void setStart_time(Long start_time) {
        this.start_time = start_time;
    }

    public Integer getStep_goal() {
        return step_goal;
    }

    public void setStep_goal(Integer step_goal) {
        this.step_goal = step_goal;
    }

    public Integer getNext_step_goal() {
        return next_step_goal;
    }

    public void setNext_step_goal(Integer next_step_goal) {
        this.next_step_goal = next_step_goal;
    }


    public void setDistance_unit(Integer distance_unit) {
        this.distance_unit = distance_unit;
    }

    public Boolean getIsprofileset() {
        return isprofileset;
    }

    public void setIsprofileset(Boolean isprofileset) {
        this.isprofileset = isprofileset;
    }

    public Long getStepsynctime() {
        return stepsynctime;
    }

    public void setStepsynctime(Long stepsynctime) {
        this.stepsynctime = stepsynctime;
    }

    public Long getEcgsynctime() {
        return ecgsynctime;
    }

    public void setEcgsynctime(Long ecgsynctime) {
        this.ecgsynctime = ecgsynctime;
    }

    public byte[] getPhotodata() {
        return photodata;
    }

    public void setPhotodata(byte[] photodata) {
        this.photodata = photodata;
    }

    // KEEP METHODS - put your custom methods here
    ////bug 23050802, heightInCM and  weightInKG maybe null
    public Integer getHeight() {
        if(height == null){
            height = 170;
            Log.e("profile exception", "height is null");
        }
        return height;
    }
    public Integer getWeight() {
        if(weight == null){
            weight = 70;
            Log.e("profile exception", "weight is null");
        }
        return weight;
    }
    public String getPhoto_path() {
        if(photo_path == null)
        {
            photo_path = "";
        }
        return photo_path;
    }
    public Integer getHeight_unit() {
        if(height_unit == null)
        {
            height_unit = ProfileHelper.HEIGHT_UNIT_CM;
        }
        return height_unit;
    }
    public Integer getWeight_unit() {
        if(weight_unit == null)
        {
            weight_unit = ProfileHelper.WEIGHT_UNIT_KG;
        }
        return weight_unit;
    }
    public Integer getDistance_unit() {
        if(distance_unit == null)
        {
            distance_unit = ProfileTable.DISTANTCE_UNIT_KM;
        }
        return distance_unit;
    }
    // KEEP METHODS END

}
