package com.asus.wellness.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table sleep.
 */
public class Sleep {

    private Long id;
    private long start;
    private Long end;
    private String date;
    private String data;

    public Sleep() {
    }

    public Sleep(Long id) {
        this.id = id;
    }

    public Sleep(Long id, long start, Long end, String date, String data) {
        this.id = id;
        this.start = start;
        this.end = end;
        this.date = date;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getStart() {
        return start;
    }

    public void setStart(long start) {
        this.start = start;
    }

    public Long getEnd() {
        return end;
    }

    public void setEnd(Long end) {
        this.end = end;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
