package com.asus.wellness.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table step_count.
 */
public class Step_count {

    private Long id;
    private Long start;
    private Long end;
    private Long step_count;
    private Long sensor_value;

    public Step_count() {
    }

    public Step_count(Long id) {
        this.id = id;
    }

    public Step_count(Long id, Long start, Long end, Long step_count, Long sensor_value) {
        this.id = id;
        this.start = start;
        this.end = end;
        this.step_count = step_count;
        this.sensor_value = sensor_value;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getStart() {
        return start;
    }

    public void setStart(Long start) {
        this.start = start;
    }

    public Long getEnd() {
        return end;
    }

    public void setEnd(Long end) {
        this.end = end;
    }

    public Long getStep_count() {
        return step_count;
    }

    public void setStep_count(Long step_count) {
        this.step_count = step_count;
    }

    public Long getSensor_value() {
        return sensor_value;
    }

    public void setSensor_value(Long sensor_value) {
        this.sensor_value = sensor_value;
    }

}
