package com.asus.wellness.dbhelper;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.asus.wellness.dbhelper.Device;
import com.asus.wellness.dbhelper.Profile;
import com.asus.wellness.dbhelper.Activity_state;
import com.asus.wellness.dbhelper.Ecg;
import com.asus.wellness.dbhelper.Step_goal;
import com.asus.wellness.dbhelper.Location_change;
import com.asus.wellness.dbhelper.Coach;
import com.asus.wellness.dbhelper.Sleep;

import com.asus.wellness.dbhelper.DeviceDao;
import com.asus.wellness.dbhelper.ProfileDao;
import com.asus.wellness.dbhelper.Activity_stateDao;
import com.asus.wellness.dbhelper.EcgDao;
import com.asus.wellness.dbhelper.Step_goalDao;
import com.asus.wellness.dbhelper.Location_changeDao;
import com.asus.wellness.dbhelper.CoachDao;
import com.asus.wellness.dbhelper.SleepDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceDaoConfig;
    private final DaoConfig profileDaoConfig;
    private final DaoConfig activity_stateDaoConfig;
    private final DaoConfig ecgDaoConfig;
    private final DaoConfig step_goalDaoConfig;
    private final DaoConfig location_changeDaoConfig;
    private final DaoConfig coachDaoConfig;
    private final DaoConfig sleepDaoConfig;

    private final DeviceDao deviceDao;
    private final ProfileDao profileDao;
    private final Activity_stateDao activity_stateDao;
    private final EcgDao ecgDao;
    private final Step_goalDao step_goalDao;
    private final Location_changeDao location_changeDao;
    private final CoachDao coachDao;
    private final SleepDao sleepDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        profileDaoConfig = daoConfigMap.get(ProfileDao.class).clone();
        profileDaoConfig.initIdentityScope(type);

        activity_stateDaoConfig = daoConfigMap.get(Activity_stateDao.class).clone();
        activity_stateDaoConfig.initIdentityScope(type);

        ecgDaoConfig = daoConfigMap.get(EcgDao.class).clone();
        ecgDaoConfig.initIdentityScope(type);

        step_goalDaoConfig = daoConfigMap.get(Step_goalDao.class).clone();
        step_goalDaoConfig.initIdentityScope(type);

        location_changeDaoConfig = daoConfigMap.get(Location_changeDao.class).clone();
        location_changeDaoConfig.initIdentityScope(type);

        coachDaoConfig = daoConfigMap.get(CoachDao.class).clone();
        coachDaoConfig.initIdentityScope(type);

        sleepDaoConfig = daoConfigMap.get(SleepDao.class).clone();
        sleepDaoConfig.initIdentityScope(type);

        deviceDao = new DeviceDao(deviceDaoConfig, this);
        profileDao = new ProfileDao(profileDaoConfig, this);
        activity_stateDao = new Activity_stateDao(activity_stateDaoConfig, this);
        ecgDao = new EcgDao(ecgDaoConfig, this);
        step_goalDao = new Step_goalDao(step_goalDaoConfig, this);
        location_changeDao = new Location_changeDao(location_changeDaoConfig, this);
        coachDao = new CoachDao(coachDaoConfig, this);
        sleepDao = new SleepDao(sleepDaoConfig, this);

        registerDao(Device.class, deviceDao);
        registerDao(Profile.class, profileDao);
        registerDao(Activity_state.class, activity_stateDao);
        registerDao(Ecg.class, ecgDao);
        registerDao(Step_goal.class, step_goalDao);
        registerDao(Location_change.class, location_changeDao);
        registerDao(Coach.class, coachDao);
        registerDao(Sleep.class, sleepDao);
    }
    
    public void clear() {
        deviceDaoConfig.getIdentityScope().clear();
        profileDaoConfig.getIdentityScope().clear();
        activity_stateDaoConfig.getIdentityScope().clear();
        ecgDaoConfig.getIdentityScope().clear();
        step_goalDaoConfig.getIdentityScope().clear();
        location_changeDaoConfig.getIdentityScope().clear();
        coachDaoConfig.getIdentityScope().clear();
        sleepDaoConfig.getIdentityScope().clear();
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public ProfileDao getProfileDao() {
        return profileDao;
    }

    public Activity_stateDao getActivity_stateDao() {
        return activity_stateDao;
    }

    public EcgDao getEcgDao() {
        return ecgDao;
    }

    public Step_goalDao getStep_goalDao() {
        return step_goalDao;
    }

    public Location_changeDao getLocation_changeDao() {
        return location_changeDao;
    }

    public CoachDao getCoachDao() {
        return coachDao;
    }

    public SleepDao getSleepDao() {
        return sleepDao;
    }

}
