package com.asus.wellness.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table profile.
 */
public class Profile {

    private Long id;
    private String name;
    private String photo_path;
    private Integer age;
    private Integer gender;
    private Integer height;
    private Integer height_unit;
    private Integer weight;
    private Integer weight_unit;
    private Long start_time;
    private Integer distance_unit;
    private Long birthday;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Profile() {
    }

    public Profile(Long id) {
        this.id = id;
    }

    public Profile(Long id, String name, String photo_path, Integer age, Integer gender, Integer height, Integer height_unit, Integer weight, Integer weight_unit, Long start_time, Integer distance_unit, Long birthday) {
        this.id = id;
        this.name = name;
        this.photo_path = photo_path;
        this.age = age;
        this.gender = gender;
        this.height = height;
        this.height_unit = height_unit;
        this.weight = weight;
        this.weight_unit = weight_unit;
        this.start_time = start_time;
        this.distance_unit = distance_unit;
        this.birthday = birthday;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoto_path() {
        return photo_path;
    }

    public void setPhoto_path(String photo_path) {
        this.photo_path = photo_path;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getGender() {
        return gender;
    }

    public void setGender(Integer gender) {
        this.gender = gender;
    }

    public Integer getHeight() {
        return height;
    }

    public void setHeight(Integer height) {
        this.height = height;
    }

    public Integer getHeight_unit() {
        return height_unit;
    }

    public void setHeight_unit(Integer height_unit) {
        this.height_unit = height_unit;
    }

    public Integer getWeight() {
        return weight;
    }

    public void setWeight(Integer weight) {
        this.weight = weight;
    }

    public Integer getWeight_unit() {
        return weight_unit;
    }

    public void setWeight_unit(Integer weight_unit) {
        this.weight_unit = weight_unit;
    }


    public void setStart_time(Long start_time) {
        this.start_time = start_time;
    }


    public void setDistance_unit(Integer distance_unit) {
        this.distance_unit = distance_unit;
    }


    public void setBirthday(Long birthday) {
        this.birthday = birthday;
    }

    // KEEP METHODS - put your custom methods here
    public Long getStart_time() {
        if(start_time == null){
            return 0L;
        }
        return start_time;
    }

    public Integer getDistance_unit() {
        if(distance_unit == null){
            return 0;
        }
        return distance_unit;
    }

    public Long getBirthday() {
        if(birthday == null){
            return 0L;
        }
        return birthday;
    }
    // KEEP METHODS END

}
