package com.asus.wellness.dbhelper;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table step_goal.
 */
public class Step_goal {

    private Long id;
    private String date_milli;
    private Long step_goal;

    public Step_goal() {
    }

    public Step_goal(Long id) {
        this.id = id;
    }

    public Step_goal(Long id, String date_milli, Long step_goal) {
        this.id = id;
        this.date_milli = date_milli;
        this.step_goal = step_goal;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDate_milli() {
        return date_milli;
    }

    public void setDate_milli(String date_milli) {
        this.date_milli = date_milli;
    }

    public Long getStep_goal() {
        return step_goal;
    }

    public void setStep_goal(Long step_goal) {
        this.step_goal = step_goal;
    }

}
